# Generated by Django 5.2.8 on 2025-11-24 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educacion',
            name='profesor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='educacion', to='academics.profesor'),
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoevaluaciones', to='academics.profesor'),
        ),
        migrations.AddField(
            model_name='profesoruea',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ueas', to='academics.profesor'),
        ),
        migrations.AddField(
            model_name='recuperacion',
            name='espacio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recuperacion', to='academics.espacio'),
        ),
        migrations.AddField(
            model_name='uea',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.grupo'),
        ),
        migrations.AddField(
            model_name='uea',
            name='licenciaturas',
            field=models.ManyToManyField(related_name='ueas', through='academics.LicenciaturaUEA', to='academics.licenciatura'),
        ),
        migrations.AddField(
            model_name='recuperacion',
            name='uea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recuperacion', to='academics.uea'),
        ),
        migrations.AddField(
            model_name='profesoruea',
            name='uea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='academics.uea'),
        ),
        migrations.AddField(
            model_name='licenciaturauea',
            name='uea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.uea'),
        ),
        migrations.AddField(
            model_name='cartatematica',
            name='uea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carta_tematica', to='academics.uea'),
        ),
        migrations.AlterUniqueTogether(
            name='profesoruea',
            unique_together={('profesor', 'uea')},
        ),
        migrations.AlterUniqueTogether(
            name='licenciaturauea',
            unique_together={('licenciatura', 'uea')},
        ),
    ]
